// Auto-generated voice configuration
// DO NOT EDIT - Generated by scripts/generate-voices.py

export interface VoiceCharacter {
  id: string;
  name: string;
  description: string;
  credit: string;
}

export const VOICE_CHARACTERS: VoiceCharacter[] = [
  {
    "id": "metan",
    "name": "四国めたん",
    "description": "元氣可愛的少女聲音",
    "credit": "VOICEVOX:四国めたん"
  },
  {
    "id": "tsumugi",
    "name": "春日部つむぎ",
    "description": "溫柔甜美的少女聲音",
    "credit": "VOICEVOX:春日部つむぎ"
  },
  {
    "id": "sora",
    "name": "九州そら",
    "description": "開朗活潑的少女聲音",
    "credit": "VOICEVOX:九州そら"
  }
];

export const VOICE_TERMS_LINKS = {
  metan: "https://zunko.jp/con_ongen_kiyaku.html",
  tsumugi: "https://virvoxproject.wixsite.com/official/tsumugi",
  sora: "https://zunko.jp/con_ongen_kiyaku.html"
};
