// Auto-generated voice configuration
// DO NOT EDIT - Generated by scripts/generate-voices.py

export interface VoiceCharacter {
  id: string;
  name: string;
  description: string;
  credit: string;
}

export const VOICE_CHARACTERS: VoiceCharacter[] = [
  {
    "id": "metan",
    "name": "四国めたん",
    "description": "元氣可愛的少女聲音",
    "credit": "VOICEVOX:四国めたん"
  },
  {
    "id": "tsumugi",
    "name": "春日部つむぎ",
    "description": "溫柔甜美的少女聲音",
    "credit": "VOICEVOX:春日部つむぎ"
  },
  {
    "id": "hau",
    "name": "雨晴はう",
    "description": "活潑開朗的少女聲音",
    "credit": "VOICEVOX:雨晴はう"
  }
];

export const VOICE_TERMS_LINKS = {
  metan: "https://zunko.jp/con_ongen_kiyaku.html",
  tsumugi: "https://tsukushinyoki.seesaa.net/article/498559636.html", 
  hau: "https://amehau.com/"
};
